update JournalSpendCategory set description = 'Grounds Maintenance' where spendCategory = 'SC257'
update JournalSpendCategory set description = 'Building-Construction Costs' where spendCategory = 'SC368'
update JournalSpendCategory set description = 'Hazardous Material Removal (FIN47)' where spendCategory = 'SC242'
update JournalSpendCategory set description = 'Fixed Equipment-10 yr life' where spendCategory = 'SC018'
update JournalSpendCategory set description = 'Moveable Equipment-05 yr life' where spendCategory = 'SC023'
update JournalSpendCategory set description = 'Specimens & Collections' where spendCategory = 'SC463'
update JournalSpendCategory set description = 'Land Improvements' where spendCategory = 'SC276'
update JournalSpendCategory set description = 'Land' where spendCategory = 'SC377'
update JournalSpendCategory set description = 'Building-Professional Fees & Reimbursables' where spendCategory = 'SC369'
update JournalSpendCategory set description = 'Design Construction Administration' where spendCategory = 'SC373'
update JournalSpendCategory set description = 'Building Capital Projects Softcosts' where spendCategory = 'SC375'
update JournalSpendCategory set description = 'Fixed Equipment-15 yr life' where spendCategory = 'SC019'
update JournalSpendCategory set description = 'Moveable Equipment-08 yr life' where spendCategory = 'SC026'
update JournalSpendCategory set description = 'Moveable Equipment-10 yr life' where spendCategory = 'SC027'
update JournalSpendCategory set description = 'Moveable Equipment-15 yr life' where spendCategory = 'SC029'
update JournalSpendCategory set description = 'Vehicles 04 yr life' where spendCategory = 'SC031'
update JournalSpendCategory set description = 'Minor Equipment' where spendCategory = 'SC168'
update JournalSpendCategory set description = 'Property/Real Estate Assessments' where spendCategory = 'SC245'
update JournalSpendCategory set description = 'Moving Expenses-Offices' where spendCategory = 'SC258'
update JournalSpendCategory set description = 'Other Moving Expenses' where spendCategory = 'SC265'
update JournalSpendCategory set description = 'Hazardous Material Removal (FIN47)' where spendCategory = 'SC484'
update JournalSpendCategory set description = 'Environmental Surveys/Sampling' where spendCategory = 'SC486'
update JournalSpendCategory set description = 'Storage' where spendCategory = 'SC488'
update JournalSpendCategory set description = 'Furnishings <$5,000' where spendCategory = 'SC489'
update JournalSpendCategory set description = 'Worker transportation' where spendCategory = 'SC490'
update JournalSpendCategory set description = 'TEMP for testing' where spendCategory = 'SC205'
update JournalSpendCategory set description = 'TEMP for testing' where spendCategory = 'SC237'
update JournalSpendCategory set description = 'TEMP for testing' where spendCategory = 'SC206'
update JournalSpendCategory set description = 'TEMP for testing' where spendCategory = 'SC335'
update JournalSpendCategory set description = 'TEMP for testing' where spendCategory = 'SC192'